/*
* This file is automatically generated.
* Do not modify! -- ALL CHANGES WILL BE ERASED!
*/

package net.thauvin.erik.akismet

/**
* Provides semantic version information.
*/
internal object GeneratedVersion {
    const val PROJECT = "Akismet Kotlin"
    const val VERSION = "1.1.0-SNAPSHOT"
}
